# Generated by Django 5.2.17 on 2026-09-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('repo', models.CharField(blank=True, help_text='owner/repo', max_length=200)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=40)),
                ('sample_message', models.TextField()),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='detector.project')),
            ],
        ),
        migrations.CreateModel(
            name='CIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
                ('run_attempt', models.PositiveSmallIntegerField(default=1)),
                ('job_name', models.CharField(blank=True, max_length=100)),
                ('commit_sha', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=200)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='detector.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=300)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('flaky', 'Flaky'), ('suspect', 'Suspect'), ('stable', 'Stable'), ('insufficient_data', 'Insufficient')], default='insufficient_data', max_length=20)),
                ('flakiness_score', models.FloatField(blank=True, null=True)),
                ('executions', models.PositiveIntegerField(default=0)),
                ('conflict_commits', models.PositiveIntegerField(default=0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('flip_rate', models.FloatField(default=0.0)),
                ('score_computed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='detector.project')),
            ],
        ),
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detector.cirun')),
                ('error_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='detector.errorgroup')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detector.trackedtest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='errorgroup',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='uniq_error_fp'),
        ),
        migrations.AddIndex(
            model_name='cirun',
            index=models.Index(fields=['project', 'commit_sha'], name='detector_ci_project_58bac5_idx'),
        ),
        migrations.AddIndex(
            model_name='cirun',
            index=models.Index(fields=['project', 'started_at'], name='detector_ci_project_3bf6ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='cirun',
            constraint=models.UniqueConstraint(fields=('project', 'run_id', 'run_attempt', 'job_name'), name='uniq_ci_run'),
        ),
        migrations.AddIndex(
            model_name='trackedtest',
            index=models.Index(fields=['project', '-flakiness_score'], name='detector_tr_project_f50304_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedtest',
            index=models.Index(fields=['project', 'status'], name='detector_tr_project_699ec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackedtest',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_test_per_project'),
        ),
        migrations.AddIndex(
            model_name='caseresult',
            index=models.Index(fields=['test', 'executed_at'], name='detector_ca_test_id_d17190_idx'),
        ),
        migrations.AddIndex(
            model_name='caseresult',
            index=models.Index(fields=['test', 'outcome'], name='detector_ca_test_id_c82b74_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseresult',
            constraint=models.UniqueConstraint(fields=('run', 'test'), name='uniq_result_per_run'),
        ),
    ]
