# Generated by Django 5.2.17 on 2026-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedtest',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackedtest',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
