# Generated by Django 5.2.17 on 2026-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_trackedtest_quarantined_trackedtest_quarantined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Email address for flaky-test alerts.', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='slack_webhook_url',
            field=models.URLField(blank=True, help_text='Incoming webhook URL for flaky-test alerts.'),
        ),
    ]
